---
title: "Final Density Plots"
author: "Kaitlin Rommelfanger"
date: "2023-11-03"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r Boxplots y axes Different Scales}
#libraries
library(tidyverse)
library(patchwork)
#csvs needed
#seagrass information
grass<-read.csv("Data/WeFixedItAnalyzeMe.csv")
#fish family information
fish<-read.csv("Data/AllMerged.csv")


##Seagrass
#adding a totalgrass column, sum of all grass present, and calculating the percent of present seagrass that is halophila 
grass<-grass %>% 
  mutate(totalgrass=(grass$PCovHalophila+
                       grass$PCovThalassia+
                       grass$PCovHalodule+
                       grass$PCovSyringodium)) %>% 
  mutate(PerHalTotal=(grass$PCovHalophila/
                        totalgrass))

#remove transects that dont have any seagrass
grass<-grass%>%
  filter(totalgrass!=0)

##Make the depth bin categories##
grass<- grass%>% 
       mutate(dhcat = case_when((depth >= 15.0) ~ "deep",
                                (depth <= 15.0 & PerHalTotal == 1.0) ~ "hal",
                                (depth <= 15.0 & PerHalTotal < 1.0) ~ "native" ))


#count of number of fish in each family on each transect, want tabular by transect, replaced NA with zeros

fishdens<-fish%>%
  group_by(Transect)%>%
  count(Family)%>%
  pivot_wider(names_from = Family, values_from = n)%>%
  mutate_all(~replace(., is.na(.), 0))

#selected the families contributing to 90% of the differences between all groups, then determined density of each family, by taking the total count of each family divided by 100 which is the area of the transects
  fishdens<-fishdens%>%select(Transect, 
                              Labridae, 
                              Lutjanidae, 
                              Gobiidae, 
                              Serranidae, 
                              Scaridae, 
                              Labrisomidae, 
                              Carangidae, 
                              Pomacentridae, 
                              Monacanthidae )%>%
    mutate("Lab"=Labridae/100, 
                                  "Lut"=Lutjanidae/100,
                                  "Gob"=Gobiidae/100,
                                  "Ser"=Serranidae/100,
                                  "Scar"=Scaridae/100,
                                  "Labm"=Labrisomidae/100,
                                  "Car"=Carangidae/100,
                                  "Pom"=Pomacentridae/100,
                                  "Mon"=Monacanthidae/100)
  


#now merge the two dataframes, so we know the categories and the densities 

  fgmerge<-merge(fishdens, grass[,c("Transect", "dhcat")], by="Transect")

#select columns we want to plot the data, transect, all the densities and the category
plotframe <- fgmerge%>%select(Transect, 
                              Lab, 
                              Lut, 
                              Gob, 
                              Ser, 
                              Scar, 
                              Labm, 
                              Car, 
                              Pom, 
                              Mon, 
                              dhcat)

#now pivot dataframe longer, for plotting, and make the category a factor
plotframe <- plotframe%>%
  pivot_longer(cols = Lab:Mon,
               names_to = "Family",
               values_to = "density")%>%
  mutate(dhcat = as.factor(dhcat))



#get one boxplot working, look how we want it 

Gob<-plotframe%>%
    filter(Family=="Gob")%>%
    ggplot(names=labels, aes(x=dhcat, y=density, fill=dhcat))+
  geom_boxplot(outlier.shape=2)+#change the shape of outliers
  geom_point(size=0.6)+#adds the points onto plot in single line
  xlab(" ")+#no x axis labels 
  ylab(" ")+#no y axis lables
  ggtitle("Gobiidae")+
  theme(plot.title = element_text(hjust = 0.5))+#how to center the title
  scale_fill_manual(name = "Category", labels = c(">15m", "< 15m & 100% Halophila","< 15m & Native Present"),values = c("#56B4E9","#F0E442","#CC79A7"))+#pick the colors
  scale_x_discrete(labels=c(">15m", "< 15m & \n 100% Halophila","<15m & \n  Native Present"))+geom_text(aes(family="serif", fontface="plain"),x= "deep" , y=0.27, label="a")+#add first letter, family and fontface change font and remove bold
  geom_text(aes(family="serif", fontface="plain"),x= "hal" , y=0.25, label="ab")+#add second letter
  geom_text(aes(family="serif", fontface="plain"), x= "native" , y=0.2, label="b")+#add third letter 
  theme(legend.position="none",panel.background = element_rect(fill = "white", colour = "grey50"),plot.title = element_text(hjust = 0.5))+#no legend, gridlines or grey background, centered title
    ylim(0,0.3)#manually set y axis 


Gob

#next plot Labridae

Lab<-plotframe%>%
    filter(Family=="Lab")%>%
    ggplot(names=labels, aes(x=dhcat, y=density, fill=dhcat))+
  geom_boxplot(outlier.shape=2)+#change the shape of outliers
  geom_point(size=0.6)+#adds the points onto plot in single line
  xlab(" ")+#no x axis labels 
  ylab("Density (fish/100m2)")+
  ggtitle("Labridae")+
  theme(plot.title = element_text(hjust = 0.5))+#how to center the title
  scale_fill_manual(name = "Category", labels = c(">15m", "< 15m & 100% Halophila","< 15m & Native Present"),values = c("#56B4E9","#F0E442","#CC79A7"))+#pick the colors
  scale_x_discrete(labels=c(">15m", "< 15m & \n 100% Halophila","<15m & \n Native Present"))+geom_text(aes(family="serif", fontface="plain"),x= "deep" , y=0.2, label="a")+#add first letter, family and fontface change font and remove bold
  geom_text(aes(family="serif", fontface="plain"),x= "hal" , y=0.3, label="b")+#add second letter
  geom_text(aes(family="serif", fontface="plain"), x= "native" , y=0.54, label="b")+#add third letter
  theme(legend.position="none",panel.background = element_rect(fill = "white", colour = "grey50"),plot.title = element_text(hjust = 0.5))+#no legend, gridlines or grey background, centered title
    ylim(0,0.55)#manually set y axis 
  
Lab
#next plot Lutjanidae 

Lut<-plotframe%>%
    filter(Family=="Lut")%>%
    ggplot(names=labels, aes(x=dhcat, y=density, fill=dhcat))+
  geom_boxplot(outlier.shape=2)+#change the shape of outliers
  geom_point(size=0.6)+#adds the points onto plot in single line
  xlab(" ")+#no x axis labels 
  ylab(" ")+
  ggtitle("Lutjanidae")+
  theme(plot.title = element_text(hjust = 0.5))+#how to center the title
  scale_fill_manual(name = "Category", labels = c(">15m", "< 15m & 100% Halophila","< 15m & Native Present"),values = c("#56B4E9","#F0E442","#CC79A7"))+#pick the colors
  scale_x_discrete(labels=c(">15m", "< 15m & \n 100% Halophila","<15m & \n Native Present"))+geom_text(aes(family="serif", fontface="plain"),x= "deep" , y=0.4, label="a")+#add first letter, family and fontface change font and remove bold
  geom_text(aes(family="serif", fontface="plain"),x= "hal" , y=0.2, label="b")+#add second letter
  geom_text(aes(family="serif", fontface="plain"), x= "native" , y=0.2, label="b")+#add third letter
  theme(legend.position="none",panel.background = element_rect(fill = "white", colour = "grey50"),plot.title = element_text(hjust = 0.5))+#no legend, gridlines or grey background, centered title
    ylim(0,0.45)#manually set y axis 
  
Lut

#next is Serranidae
Ser<-plotframe%>%
    filter(Family=="Ser")%>%
    ggplot(names=labels, aes(x=dhcat, y=density, fill=dhcat))+
  geom_boxplot(outlier.shape=2)+#change the shape of outliers
  geom_point(size=0.6)+#adds the points onto plot in single line
  xlab(" ")+#no x axis labels 
  ylab("Density (fish/100m2)")+
  ggtitle("Serranidae")+
  theme(plot.title = element_text(hjust = 0.5))+#how to center the title
  scale_fill_manual(name = "Category", labels = c(">15m", "< 15m & 100% Halophila","< 15m & Native Present"),values = c("#56B4E9","#F0E442","#CC79A7"))+#pick the colors
  scale_x_discrete(labels=c(">15m", "< 15m & \n 100% Halophila","<15m & \n  Native Present"))+geom_text(aes(family="serif", fontface="plain"),x= "deep" , y=0.19, label="a")+#add first letter, family and fontface change font and remove bold
  geom_text(aes(family="serif", fontface="plain"),x= "hal" , y=0.125, label="b")+#add second letter
  geom_text(aes(family="serif", fontface="plain"), x= "native" , y=0.125, label="b")+#add third letter 
 theme(legend.position="none",panel.background = element_rect(fill = "white", colour = "grey50"),plot.title = element_text(hjust = 0.5))+#no legend, gridlines or grey background, centered title
    ylim(0,0.25)#manually set y axis 
Ser

#Scaridae is next

Scar<-plotframe%>%
    filter(Family=="Scar")%>%
    ggplot(names=labels, aes(x=dhcat, y=density, fill=dhcat))+
  geom_boxplot(outlier.shape=2)+#change the shape of outliers
  geom_point(size=0.6)+#adds the points onto plot in single line
  xlab(" ")+#no x axis labels 
  ylab(" ")+#n y axis labels
  ggtitle("Scaridae")+
  theme(plot.title = element_text(hjust = 0.5))+#how to center the title
  scale_fill_manual(name = "Category", labels = c(">15m", "< 15m & 100% Halophila","< 15m & <100% Halophila"),values = c("#56B4E9","#F0E442","#CC79A7"))+#pick the colors
  scale_x_discrete(labels=c(">15m", "< 15m & \n 100% Halophila","<15m & \n Native Present"))+
  theme(legend.position="none",panel.background = element_rect(fill = "white", colour = "grey50"),plot.title = element_text(hjust = 0.5))+#no legend, gridlines or grey background, centered title
    ylim(0,0.175)#manually set y axis 

Scar

#Labrisomidae is next

Labm<-plotframe%>%
    filter(Family=="Labm")%>%
    ggplot(names=labels, aes(x=dhcat, y=density, fill=dhcat))+
  geom_boxplot(outlier.shape=2)+#change the shape of outliers
  geom_point(size=0.6)+#adds the points onto plot in single line
  xlab(" ")+#no x axis labels 
  ylab(" ")+#no y axis labels
  ggtitle("Labrisomidae")+
  theme(plot.title = element_text(hjust = 0.5))+#how to center the title
  scale_fill_manual(name = "Category", labels = c(">15m", "< 15m & 100% Halophila","< 15m & <100% Halophila"),values = c("#56B4E9","#F0E442","#CC79A7"))+#pick the colors
  scale_x_discrete(labels=c(">15m", "< 15m & \n 100% Halophila","<15m & \n Native Present"))+geom_text(aes(family="serif", fontface="plain"),x= "deep" , y=0.09, label="a")+#add first letter, family and fontface change font and remove bold
  geom_text(aes(family="serif", fontface="plain"),x= "hal" , y=0.075, label="a")+#add second letter
  geom_text(aes(family="serif", fontface="plain"), x= "native" , y=0.075, label="a")+#add third letter 
  theme(legend.position="none",panel.background = element_rect(fill = "white", colour = "grey50"),plot.title = element_text(hjust = 0.5))+#no legend, gridlines or grey background, centered title
    ylim(0,0.1)#manually set y axis 

Labm

#Car is next Carangidae
Car<-plotframe%>%
    filter(Family=="Car")%>%
    ggplot(names=labels, aes(x=dhcat, y=density, fill=dhcat))+
  geom_boxplot(outlier.shape=2)+#change the shape of outliers
  geom_point(size=0.6)+#adds the points onto plot in single line
  xlab(" ")+#no x axis labels 
  ylab("Density (fish/100m2)")+
  ggtitle("Carangidae")+
  theme(plot.title = element_text(hjust = 0.5))+#how to center the title
  scale_fill_manual(name = "Category", labels = c(">15m", "< 15m & 100% Halophila","< 15m & Native Present"),values = c("#56B4E9","#F0E442","#CC79A7"))+#pick the colors
  scale_x_discrete(labels=c(">15m", "< 15m & \n 100% Halophila","<15m & \n Native Present"))+
  theme(legend.position="none",panel.background = element_rect(fill = "white", colour = "grey50"),plot.title = element_text(hjust = 0.5))+#no legend, gridlines or grey background, centered title
    ylim(0,0.65)#manually set y axis 
  
Car

#next is  Pomacentridae

Pom<-plotframe%>%
    filter(Family=="Pom")%>%
    ggplot(names=labels, aes(x=dhcat, y=density, fill=dhcat))+
  geom_boxplot(outlier.shape=2)+#change the shape of outliers
  geom_point(size=0.6)+#adds the points onto plot in single line
  xlab(" ")+#no x axis labels 
  ylab(" ")+#n y axis labels
  ggtitle("Pomacentridae")+
  theme(plot.title = element_text(hjust = 0.5))+#how to center the title
  scale_fill_manual(name = "Category", labels = c(">15m", "< 15m & 100% Halophila","< 15m & Native Present"),values = c("#56B4E9","#F0E442","#CC79A7"))+#pick the colors
  scale_x_discrete(labels=c(">15m", "< 15m & \n 100% Halophila","<15m & \n Native Present"))+theme(legend.position="none")+#removes legend 
    ylim(0,0.12)+#manually set y axis 
  geom_text(aes(family="serif", fontface="plain"),x= "deep" , y=0.09, label="a")+#add first letter, family and fontface change font and remove bold
  geom_text(aes(family="serif", fontface="plain"),x= "hal" , y=0.075, label="b")+#add second letter
  geom_text(aes(family="serif", fontface="plain"), x= "native" , y=0.075, label="a")+#add third letter 
  theme(legend.position="none",panel.background = element_rect(fill = "white", colour = "grey50"),plot.title = element_text(hjust = 0.5))+#no legend, gridlines or grey background, centered title
    ylim(0,0.1)#manually set y axis 
  
Pom

#next is Monacanthidae

Mon<-plotframe%>%
    filter(Family=="Mon")%>%
    ggplot(names=labels, aes(x=dhcat, y=density, fill=dhcat))+
  geom_boxplot(outlier.shape=2)+#change the shape of outliers
  geom_point(size=0.6)+#adds the points onto plot in single line
  xlab(" ")+#no x axis labels 
  ylab(" ")+#no y axis labels
  ggtitle("Monacanthidae")+
  theme(plot.title = element_text(hjust = 0.5))+#how to center the title
  scale_fill_manual(name = "Category", labels = c(">15m", "< 15m & 100% Halophila","< 15m & Native Present"),values = c("#56B4E9","#F0E442","#CC79A7"))+#pick the colors
  scale_x_discrete(labels=c(">15m", "< 15m & \n 100% Halophila","<15m & \n Native Present"))+
  theme(panel.background = element_rect(fill = "white", colour = "grey50"),plot.title = element_text(hjust = 0.5))+#no legend, gridlines or grey background, centered title
    ylim(0,0.035)#manually set y axis 
  
Mon

#patchwork help  https://gotellilab.github.io/GotelliLabMeetingHacks/NickGotelli/ggplotPatchwork.html
DifferentScales<-Lab+Lut+Gob+Ser+Scar+Labm+Car+Pom+Mon+plot_layout(ncol=3)

DifferentScales
```


```{r}

library(ggforce)

Gob<-plotframe%>%
    filter(Family=="Gob")%>%
    ggplot(names=labels, aes(x=dhcat, y=density, fill=dhcat))+
  geom_violin()+
  geom_sina()+
  geom_boxplot(fill=NA,alpha=0,width=0.1)+
  xlab(" ")+#no x axis labels 
  ylab(" ")+#no y axis lables
  ggtitle("Gobiidae")+
  theme(plot.title = element_text(hjust = 0.5))+#how to center the title
  scale_fill_manual(name = "Category", labels = c(">15m", "< 15m & 100% Halophila","< 15m & Native Present"),values = c("#56B4E9","#F0E442","#CC79A7"))+#pick the colors
  scale_x_discrete(labels=c(">15m", "< 15m & \n 100% Halophila","<15m & \n  Native Present"))+
  geom_text(aes(family="serif", fontface="plain"),x= "deep" , y=0.27, label="a")+#add first letter, family and fontface change font and remove bold
  geom_text(aes(family="serif", fontface="plain"),x= "hal" , y=0.25, label="ab")+#add second letter
  geom_text(aes(family="serif", fontface="plain"), x= "native" , y=0.2, label="b")+#add third letter 
  theme(legend.position="none",panel.background = element_rect(fill = "white", colour = "grey50"),plot.title = element_text(hjust = 0.5))+#no legend, gridlines or grey background, centered title
    ylim(0,0.3)#manually set y axis 

Gob

```




```{r Compare Snapper Densities}
library(readr)
library(tidyverse)
library(patchwork)
#import csv
AllMerged<- read_csv("Data/AllMerged.csv")

#total count of each type of fish on each transect, select for snappers, then calculate density
snap<-AllMerged %>%
  group_by(Transect)%>%
  count(Common.Names)%>%
  pivot_wider(names_from = Common.Names , values_from = n)%>%
   select("Transect", 
          "Yellowtail Snapper", 
          "Lane Snapper", 
          "Cubera Snapper")%>%mutate(ysdens=`Yellowtail Snapper`/100,
                                     lsdens=`Lane Snapper`/100,
                                     csdens=`Cubera Snapper`/100)%>%
  select(Transect,
         ysdens, 
         lsdens, 
         csdens)

##Turning NAs to 0s
snap[is.na(snap)] <- 0


#pivot longer for analysis/plotting
snap<-snap%>%
  pivot_longer(cols = ysdens:csdens,
               names_to = "Species",
               values_to = "density")

#importing the information for categories
categories<- read_csv("Final Code and Plots/Data/WeFixedItAnalyzeMe.csv")

#make a total grass, and percent of grass that is Halophila column
grass<-categories %>%
  mutate(totalgrass= (PCovHalophila+
                        PCovThalassia+
                        PCovHalodule+
                        PCovSyringodium)) %>%
  mutate(PerHalTotal=(PCovHalophila/totalgrass))

##remove the transects with no seagrass
grass<-grass%>%
  filter(totalgrass!=0)

##Make a category column##
 grass <- grass %>%
       mutate(dcat = case_when((depth >= 15.0) ~ "deep",
                                (depth <= 15.0 & PerHalTotal == 1.0) ~ "hal",
                                (depth <= 15.0 & PerHalTotal < 1.0) ~ "native" ))%>%
   select(Transect, dcat)

#now we merge with our fish info, so we have cat info
snapsbro<- merge(grass, snap, by= "Transect")

#get yellowtail boxplot working, look how we want it 

YT<-snapsbro%>%
    filter(Species=="ysdens")%>%
    ggplot(names=labels, aes(x=dcat, y=density, fill=dcat))+
  geom_boxplot(outlier.shape=2)+#change the shape of outliers
  geom_point(size=0.6)+#adds the points onto plot in single line
  xlab(" ")+#no x axis labels 
  ylab("Density (individuals/100m2)")+
  ggtitle("Ocyurus chrysurus")+
  theme(plot.title = element_text(hjust = 0.5))+#how to center the title
  scale_fill_manual(name = "Category", labels = c(">15m", "< 15m & 100% Halophila","< 15m & Native Present"),values = c("#56B4E9","#F0E442","#CC79A7"))+#pick the colors
  scale_x_discrete(labels=c(">15m", "< 15m & \n 100% Halophila","<15m & \n Native Present"))+geom_text(aes(family="serif", fontface="plain"),x= "deep" , y=0.35, label="a")+#add first letter, family and fontface change font and remove bold
  geom_text(aes(family="serif", fontface="plain"),x= "hal" , y=0.2, label="b")+#add second letter
  geom_text(aes(family="serif", fontface="plain"), x= "native" , y=0.2, label="b")+#add third letter 
theme(legend.position="none",panel.background = element_rect(fill = "white", colour = "grey50"),plot.title = element_text(hjust = 0.5))#no legend, no gridlines or grey background, centered title
  

YT

#lane snapper
LS<-snapsbro%>%
    filter(Species=="lsdens")%>%
    ggplot(names=labels, aes(x=dcat, y=density, fill=dcat))+
  geom_boxplot(outlier.shape=2)+#change the shape of outliers
  geom_point(size=0.6)+#adds the points onto plot in single line
  xlab(" ")+#no x axis labels 
  ylab(" ")+
  ggtitle("Lutjanus synagris")+
  theme(plot.title = element_text(hjust = 0.5))+#how to center the title
  scale_fill_manual(name = "Category", labels = c(">15m", "< 15m & 100% Halophila","< 15m & Native Present"),values = c("#56B4E9","#F0E442","#CC79A7"))+#pick the colors
  scale_x_discrete(labels=c(">15m", "< 15m & \n 100% Halophila","<15m & \n Native Present"))+geom_text(aes(family="serif", fontface="plain"),x= "deep" , y=0.11, label="a")+#add first letter, family and fontface change font and remove bold
  geom_text(aes(family="serif", fontface="plain"),x= "hal" , y=0.05, label="ab")+#add second letter
  geom_text(aes(family="serif", fontface="plain"), x= "native" , y=0.05, label="b")+#add third letter 
  theme(legend.position="none",panel.background = element_rect(fill = "white", colour = "grey50"),plot.title = element_text(hjust = 0.5))#no legend, no gridlines or grey background, centered title
  

LS

#Cubera Snapper
CS<-snapsbro%>%
    filter(Species=="csdens")%>%
    ggplot(names=labels, aes(x=dcat, y=density, fill=dcat))+
  geom_boxplot(outlier.shape=2)+#change the shape of outliers
  geom_point(size=0.6)+#adds the points onto plot in single line
  xlab(" ")+#no x axis labels 
  ylab("Density (individuals/100m2)")+#no y axis label
  ggtitle("Lutjanus cyanopterus")+
  theme(plot.title = element_text(hjust = 0.5))+#how to center the title
  scale_fill_manual(name = "Category", labels = c(">15m", "< 15m & 100% Halophila","< 15m & Native Present"),values = c("#56B4E9","#F0E442","#CC79A7"))+#pick the colors
  scale_x_discrete(labels=c(">15m", "< 15m & \n 100% Halophila","<15m & \n Native Present"))+
  theme(legend.position="none",panel.background = element_rect(fill = "white", colour = "grey50"),plot.title = element_text(hjust = 0.5))#no legend, no gridlines or grey background, centered title
  
CS

#Lutjanidae plot with legend for patchwork, need to run above code first before making this plot, just to make the dataframes that are needed 

#look at Lutjanidae plot to see what is needed
Lut1<-plotframe%>%
    filter(Family=="Lut")%>%
    ggplot(names=labels, aes(x=dhcat, y=density, fill=dhcat))+
  geom_boxplot(outlier.shape=2)+#change the shape of outliers
  geom_point(size=0.6)+#adds the points onto plot in single line
  xlab(" ")+#no x axis labels 
  ylab(" ")+
  ggtitle("Lutjanidae")+
  theme(plot.title = element_text(hjust = 0.5))+#how to center the title
  scale_fill_manual(name = "Category", labels = c(">15m", "< 15m & 100% Halophila","< 15m & Native Present"),values = c("#56B4E9","#F0E442","#CC79A7"))+#pick the colors
  scale_x_discrete(labels=c(">15m", "< 15m & \n 100% Halophila","<15m & \n Native Present"))+geom_text(aes(family="serif", fontface="plain"),x= "deep" , y=0.4, label="a")+#add first letter, family and fontface change font and remove bold
  geom_text(aes(family="serif", fontface="plain"),x= "hal" , y=0.2, label="b")+#add second letter
  geom_text(aes(family="serif", fontface="plain"), x= "native" , y=0.2, label="b")+#add third letter
  theme(panel.background = element_rect(fill = "white", colour = "grey50"),plot.title = element_text(hjust = 0.5))+#no legend, gridlines or grey background, centered title
    ylim(0,0.45)#manually set y axis 
  
Lut1
  

#combine all three plots
snap<-YT+LS+CS+Lut1
snap


```



